#!/usr/bin/env bash

# Source my color library

source ru_var_func

# Home variables

MY_EXE="$HOME/git_repos/bin"

for script in "$@"; do
	cp $script $MY_EXE 2>> $ERROR_LOG 
	if [ $? -eq 0 ]; then
		log_pass "${GREEN}SUCCESS${RESET}: Moved $script to $MY_EXE"
	else
		log_error "${RED}ERROR${RESET}: Could not locate $script in $(pwd)"
	fi
done
