#!/usr/bin/env bash

set +x

# Source color library

source my_color_lib

function set_git_username {
	echo -en "${BLUE}Enter git user.name:${RESET} "
	read -r username
	
	if [ -z "$username" ]; then
		echo -e "${RED}Invalid input... Please enter user.name${RESET}"
		exit 1
	else
		git config --global user.name "${username}"
		if [ $? -eq 0 ]; then
			echo -e "${GREEN}git user.name:${RESET} "${username}""
		fi
	fi
}

function set_git_useremail {

	echo -en "${BLUE}Enter git user.email:${RESET} "
	read -r useremail

	if [ -z "$useremail" ]; then
		echo -e "${RED}Invalid input... Please enter user.name${RESET}"
		exit 1
	else
		git config --global user.email "${useremail}"
		if [ $? -eq 0 ]; then
			echo -e "${GREEN}git user.name:${RESET} "${useremail}""
		fi
	fi
}

function set_git_branch {
	echo -en "${BLUE}Enter git defaultBranch:${RESET} "
	read -r branch

	if [ -z "$branch" ]; then
		echo -e "${RED}Invalid input... Please enter branch name${RESET}${BLUE}main${RESET}"
		exit 1
	else
		git config --global init.defaultBranch "${branch}"
		if [ $? -eq 0 ]; then
			echo -e "${GREEN}git defaultBranch:${RESET} "${branch}""
		fi
	fi
}

set_git_username
set_git_useremail
set_git_branch

echo -e "Username: $username\nUseremail: $useremail\nBranch Name: $branch"
