#!/usr/bin/env bash

# COLOR CODE ANSI

BOLD_RED="\033[1;31m"
BOLD_GREEN="\033[1;32"
BOLD_BLUE="\033[1;34m"
RESET="\033[0m"
COMMAND="git"
OPTION="commit"
ARG_2="-a"
ARG="-m"

function git_commit {

echo -e "Pushing from local repo to github\n${BOLD_BLUE}Enter Description${RESET}:"
read -r input
if [ -z "${input}" ]; then
	echo -e "${BOLD_RED}Input proper description${RESET}"
	exit 1
fi
}
function git_push_main {
	
	git commit -a -m "${input}" > /dev/null
	if [ $? -eq 0 ]; then
		echo "${BOLD_BLUE}Pushing main local repo${RESET} -> ${BOLD_GREEN}github.com/jracelis-my_learning_notes${RESET}"
		git push origin main > /dev/null
	fi
}

git_commit
git_push_main
