#!/usr/bin/env bash

# Sourcing color library

source my_color_lib

function git_commit {

echo -e "${YELLOW}Pushing from local repo to github${RESET}"
echo -en "${BLUE}Enter Description${RESET}: "
read -r input
if [ -z "${input}" ]; then
	echo -e "${RED}Input proper description${RESET}"
	exit 1
fi
}
function git_push_main {
	
	git commit -a -m "${input}" > /dev/null
	if [ $? -eq 0 ]; then
		echo -e "${BLUE}Pushing main local repo${RESET} -> ${GREEN}github.com/jracelis-my_learning_notes${RESET}"
		git push origin main > /dev/null
	fi
}

git_commit
git_push_main
