#!/usr/bin/env bash

# Color Variables

GREY="\033[1;30m"
RED="\033[1;31m"
GREEN="\033[1;32m"
YELLOW="\033[1;33m"
BLUE="\033[1;34m"
PURPLE="\033[1;35m"
CYAN="\033[1;36m"
WHITE="\033[1;37m"
RESET="\033[0m"

# Arrays variables

INDEX=0
myCOLOR=( 0 1 2 3 4 5 6 7 )
mySTYLE=( 0 1 2 3 4 5 6 7 8 )

function check_color {

	while [ $INDEX -lt ${#myCOLOR[@]} ]; do
		echo -e "\033[1;3${myCOLOR[$INDEX]}mCOLOR: 3$INDEX${RESET}"
		((INDEX++))
	done
}

function check_highlight {
	
	while [ $INDEX -lt ${#myCOLOR[@]} ]; do
		echo -e "\033[31;4${mySTYLE[$INDEX]}mHIGHLIGHT: 4$INDEX${RESET}"
		((INDEX++))
	done
}
function check_style {
	
	while [ $INDEX -lt ${#mySTYLE[@]} ]; do
		echo -e "\033[${mySTYLE[$INDEX]};31mSTYLE: $INDEX${RESET}"
		((INDEX++))
	done
}

# Remove hash to check color
# check_color
# Remove hash to check highlight
# check_highlight
# Remove hash to check style
#check_style
