#!/usr/bin/env bash

# Error log directories

TODAY="$(date +%Y-%m-%d\ %H:%M:%S)"
ERROR_LOG="$HOME/log/err_script.log"
ERROR_DIR="$HOME/log"
PASS_LOG="$HOME/log/pass_script.log"
# Color Variables

GREY="\033[1;30m"
RED="\033[1;31m"
GREEN="\033[1;32m"
YELLOW="\033[1;33m"
BLUE="\033[1;34m"
PURPLE="\033[1;35m"
CYAN="\033[1;36m"
WHITE="\033[1;37m"
RESET="\033[0m"

# Arrays variables

INDEX=0
myCOLOR=( 0 1 2 3 4 5 6 7 )
mySTYLE=( 0 1 2 3 4 5 6 7 8 )

function check_color {

	while [ $INDEX -lt ${#myCOLOR[@]} ]; do
		echo -e "\033[1;3${myCOLOR[$INDEX]}mCOLOR: 3$INDEX${RESET}"
		((INDEX++))
	done
}

function check_highlight {
	
	while [ $INDEX -lt ${#myCOLOR[@]} ]; do
		echo -e "\033[31;4${mySTYLE[$INDEX]}mHIGHLIGHT: 4$INDEX${RESET}"
		((INDEX++))
	done
}
function check_style {
	
	while [ $INDEX -lt ${#mySTYLE[@]} ]; do
		echo -e "\033[${mySTYLE[$INDEX]};31mSTYLE: $INDEX${RESET}"
		((INDEX++))
	done
}

function log_pass {
	if [ ! -d $ERROR_DIR ]; then
		mkdir $ERROR_LOG 
	fi
	echo -e "[${TODAY}] "$@"" | tee -a >&1 $PASS_LOG
}
function log_error {
	if [ ! -d $ERROR_DIR ]; then
		mkdir $ERROR_LOG 
	fi
		echo -e "[${TODAY}] "$@"" | tee -a >&2 $ERROR_LOG 
}
# Remove hash to check color
# check_color
# Remove hash to check highlight
# check_highlight
# Remove hash to check style
# check_style
